### ISSUE TITLE
Review balance in the Quarterfinals and later matches

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/compstate-smallpeice2023#4]
The initial heats have good pairing balance as teams move up the seedings. I'm not sure the quarterfinals do and haven't checked later matches.

The way I usually work this out is to assume that the better seed wins the earlier matches and then comment who each of the opponents are in the later matches (by manually parsing the reference).

**Comment by prophile** [comment]
I did work this out from a sheet so this should work, but would be good to have extra checking.
